apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-app
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
        - name: consumer-app
          image: diwelle/consumer-app:consumer-app
          

