apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-app
  namespace: kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
        - name: producer_app
          image: diwelle/consumer_app:producer_app
          

